// Export all page components for easy importing
export { default as Home } from './Home';
export { default as Services } from './Services';
export { default as Checkout } from './Checkout';
export { default as BookingConfirmation } from './BookingConfirmation';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Profile } from './Profile';
export { default as NotFound } from './NotFound';
export { default as AuthSuccess } from './AuthSuccess';
